In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("/content/fraud_transactions_synthetic.csv")

In [3]:
data.head()

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score,is_fraud
0,33.006818,15,5.500706,1,0,0,1968,1,0,0.141327,0
1,17.491861,2,45.404859,0,0,0,883,2,1,0.249084,0
2,38.385836,5,1.889033,0,0,0,257,0,0,0.175303,0
3,92.114269,19,7.925388,0,0,0,3025,3,0,0.060368,0
4,15.892489,3,45.704719,0,0,0,1651,1,0,0.274630,1

In [4]:
from sklearn.model_selection import train_test_split
#the whole data gets divided into Train Set [Make the Model Learn] and Test Set [Validate the performance]
from sklearn.metrics import confusion_matrix, accuracy_score

In [5]:
import tensorflow as tf
from tensorflow import keras #keras is a module within Tensorflow Library
from tensorflow.keras import layers #The NN will be build as a Sequential Layer of Input, Hidden and Output Layers

From the given dataset, is_fraud is the target variable or we can say the output dependent variable and all the other columns are input independent variables

In [6]:
x=data.drop(['is_fraud'],axis=1) #'x' holds all the input independent columns
y=data['is_fraud'] #'y' holds only the output dependent column

In [7]:
x.head()

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score
0,33.006818,15,5.500706,1,0,0,1968,1,0,0.141327
1,17.491861,2,45.404859,0,0,0,883,2,1,0.249084
2,38.385836,5,1.889033,0,0,0,257,0,0,0.175303
3,92.114269,19,7.925388,0,0,0,3025,3,0,0.060368
4,15.892489,3,45.704719,0,0,0,1651,1,0,0.274630

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.85)

- Whenever we are training the model it is important that we provide details about the input (x_train) as well as identify what the output looks like (y_train) because at this stage, the model is learning under supervision (Supervised ML) - that's why it is important that the model has access to both input as well as output parameters

- Whenever we are testing the performance of the model, it is important that we test the predicted output (y_pred) from input (x_test) against the actual values (y_test)

In [10]:
model=keras.Sequential(
    [
        layers.Input(shape=(x_train.shape[1],),name='input'),
        layers.Dense(32,activation='relu',name='hidden_layer_1'),
        layers.Dense(16,activation='relu',name='hidden_layer_2'),
        layers.Dense(1,activation='sigmoid',name='output_layer')
    ]
)

In [11]:
model.compile(
    optimizer='adam',
    loss=keras.losses.BinaryCrossentropy(name='binary_cross_entopy'),
    metrics=[
        keras.metrics.BinaryAccuracy(name='Accuracy'),
        keras.metrics.MeanSquaredError(name='MSE')
    ]
)

In [12]:
model.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test))

Epoch 1/10
1063/1063 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - Accuracy: 0.9003 - MSE: 0.0860 - loss: 1.2897 - val_Accuracy: 0.9405 - val_MSE: 0.0598 - val_loss: 0.3429
Epoch 2/10
1063/1063 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - Accuracy: 0.9163 - MSE: 0.0757 - loss: 0.8440 - val_Accuracy: 0.9403 - val_MSE: 0.0595 - val_loss: 0.5236
Epoch 3/10
1063/1063 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - Accuracy: 0.9117 - MSE: 0.0789 - loss: 0.9560 - val_Accuracy: 0.9408 - val_MSE: 0.0591 - val_loss: 2.2584
Epoch 4/10
1063/1063 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - Accuracy: 0.9238 - MSE: 0.0702 - loss: 0.5836 - val_Accuracy: 0.9393 - val_MSE: 0.1078 - val_loss: 0.3916
Epoch 5/10
1063/1063 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - Accuracy: 0.9214 - MSE: 0.0720 - loss: 0.6525 - val_Accuracy: 0.9408 - val_MSE: 0.0582 - val_loss: 0.2912
Epoch 6/10
1063/1063 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - Accuracy: 0.9200 - MSE: 0.0730 - loss: 0.6664 - val_Accuracy: 0.9408 - val_MSE: 0.0583 - val_loss: 0.3171
Epoch 7/10
1063/1063 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - Accuracy: 0.9209 - MSE: 0.0719 - loss: 0.5772 - val_Accuracy: 0.2663 - val_MSE: 0.4310 - val_loss: 1.1991
Epoch 8/10
1063/1063 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - Accuracy: 0.9213 - MSE: 0.0728 - loss: 0.6143 - val_Accuracy: 0.9408 - val_MSE: 0.0619 - val_loss: 0.2449
Epoch 9/10
1063/1063 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - Accuracy: 0.9308 - MSE: 0.0660 - loss: 0.4062 - val_Accuracy: 0.9408 - val_MSE: 0.0569 - val_loss: 0.2602
Epoch 10/10
1063/1063 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - Accuracy: 0.9286 - MSE: 0.0670 - loss: 0.4753 - val_Accuracy: 0.9408 - val_MSE: 0.0589 - val_loss: 0.7665